
[build]
  # Tell Netlify to run the build from this folder
  base    = "codehive-frontend"
  command = "npm run build"
  publish = "dist" 

  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200